# Generated by Django 2.2.19 on 2022-10-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20221001_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=3000, verbose_name='Текст поста'),
        ),
    ]
